[package]
name = "solana-student-intro-program"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "2.0.10"
borsh = "1.5.1"
thiserror = "1.0.63"

[lib]
crate-type = ["cdylib", "lib"]
